version: '3.8'

services:
  s3-garbage-collector-cron:
    build:
      context: ..
      dockerfile: Dockerfile
    command: gc
    environment:
      # AWS Credentials (obrigatório)
      KEY: ${AWS_ACCESS_KEY_ID}
      SECRET: ${AWS_SECRET_ACCESS_KEY}
      REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      
      # S3 Configuration (obrigatório)
      BUCKET: ${S3_BUCKET_NAME}
      BUCKET_PATH: ${S3_BUCKET_PATH:-/}
      PARAMS: ${S3BACKUP_PARAMS}
      
      # Garbage Collection Settings
      BACKUP_RETENTION_DAYS: ${BACKUP_RETENTION_DAYS:-7}
      PARAMS: ${PARAMS:-}
      DRY_RUN: ${DRY_RUN:-false}
      VERBOSE: ${VERBOSE:-true}
      
      # Cron Schedule (executa às 3h da manhã todos os dias)
      CRON_SCHEDULE: ${CRON_SCHEDULE:-0 3 * * *}
    
    # Reinicia automaticamente em caso de falha
    restart: unless-stopped
    
    # Labels para documentação
    labels:
      - "description=AWS S3 Garbage Collector - Execução periódica com cron"
      - "version=1.0.0"
    
    # Configurações de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"